CREATE TABLE symptoms (
    symptom_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    symptom_name VARCHAR2(100),
    severity VARCHAR2(20),
    duration VARCHAR2(50)
);

CREATE TABLE medical_history (
    history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    condition VARCHAR2(100),
    diagnosis_date DATE,
    description VARCHAR2(500)
);

CREATE TABLE laboratory_results (
    lab_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    glucose NUMBER(6,2),
    blood_pressure VARCHAR2(20),
    bmi NUMBER(5,2),
    cholesterol NUMBER(6,2),
    heart_rate NUMBER(3),
    test_date DATE
);

CREATE TABLE diagnosis (
    diagnosis_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    doctor_id VARCHAR2(10) REFERENCES doctor(doctor_id),
    disease VARCHAR2(100),
    diagnosis_date DATE,
    remarks VARCHAR2(500)
);

CREATE TABLE treatment (
    treatment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    doctor_id VARCHAR2(10) REFERENCES doctor(doctor_id),
    treatment_name VARCHAR2(200),
    treatment_date DATE,
    description VARCHAR2(500)
);

CREATE TABLE medication (
    medication_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR2(100) UNIQUE NOT NULL,
    category VARCHAR2(100),
    standard_dosage VARCHAR2(100)
);

CREATE TABLE patient_medication (
    patient_medication_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    medication_id NUMBER REFERENCES medication(medication_id),
    dosage VARCHAR2(100),
    start_date DATE,
    end_date DATE
);

CREATE TABLE drug_interaction (
    interaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id_1 NUMBER REFERENCES medication(medication_id),
    medication_id_2 NUMBER REFERENCES medication(medication_id),
    severity VARCHAR2(20),
    description VARCHAR2(500)
);

CREATE TABLE allergy (
    allergy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    allergen VARCHAR2(100),
    severity VARCHAR2(20),
    description VARCHAR2(500)
);

CREATE TABLE prediction (
    prediction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(10) REFERENCES patient(patient_id),
    disease VARCHAR2(100),
    risk_score NUMBER(5,2),
    risk_level VARCHAR2(20),
    prediction_date DATE DEFAULT SYSDATE,
    model_name VARCHAR2(100)
);
